### PR TITLE
Let .search return a copy of self

### PR DESCRIPTION
**Pull request by topper-123**
.search currenly modifies ``self``. This proposes creating a copy of self and modifying and returning that.

### CODE REVIEW

**Comment by laike9m** [comment]
You finally registered GitHub.

#3 also suggest this change, personally I favor his implementation. Another thing is, though I agree to return a copy, I don't really see the benefit. Previously I thought I could add some caching, but later decided not to do it, because no one really cares about the little extra memory usage.

**Comment by topper-123** [comment]
It's your repository :)

I don't like having an ``attr`` parameter in ``__init__`` though, as the end user seldomly will use this parameter, and it feels like you're exposing an implementation detail unneccarily in the ``__init__``. 

By further thought, I don't really like my ``copy.copy`` either though ( :-)), so I made new proposal, where instead the search term can be included in the ``__init__``.

And yeah, I enlisted on Pypi recently, so Github is the logical next step :-)

**Comment by topper-123** [comment]
@laike9m, My commits fail, so you should probably just ignore my pull requests untill I get the hang of Github.

**Comment by laike9m** [comment]
Never mind, pr is always welcomed.

**Comment by topper-123** [comment]
My newer solution creating a new ``PrettyDir`` object doesn't play well with use of ``sys._get_frame``, so I've deleted the branch (Hopefully correctly).

So, if you don't want to use my ``copy.copy``  proposal, I suggest using #3.

**Pull request closed without merging**
