### PR TITLE
Fix 'clean' fixture

### PR DESCRIPTION
**Pull request by kshivakumar**

### CODE REVIEW

**Comment by laike9m** [comment]
Thanks for the fix!

**Comment by laike9m** [comment]
Currently there are some test setup issue which make the test suite not able to succeed on GitHub actions..Not sure if you're also interested in taking a look
https://github.com/laike9m/pdir2/runs/5062829628?check_suite_focus=true

**Comment by kshivakumar** [comment]
@laike9m 

> Currently there are some known test setup issue which make the test suite not able to succeed on GitHub actions..I tried to search for solutions but didn't solve it. Haven't digged too deep though.
> 
> Not sure if you're also interested in taking a look https://github.com/laike9m/pdir2/runs/5062829628?check_suite_focus=true

I can look into it next week.

**Comment by laike9m** [comment]
Cool, thank you again

**Comment by kshivakumar** [comment]
@laike9m 
I can see that [Testing (3.9, ubuntu-latest)](https://github.com/laike9m/pdir2/runs/5062829628?check_suite_focus=true#logs) failed due to a `mypy` error which I will try to debug and fix, but I don't understand why other tasks are "cancelled". Is that something I need to look into as well? Or did they get cancelled because one of the tasks failed?

**Comment by laike9m** [comment]
> I can see that [Testing (3.9, ubuntu-latest)](https://github.com/laike9m/pdir2/runs/5062829628?check_suite_focus=true#logs) failed due to a mypy error which I will try to debug and fix, but I don't understand why other tasks are "cancelled". Is that something I need to look into as well? Or did they get cancelled because one of the tasks failed?

I believe they're cancelled because GitHub Actions saw a failure (3.9)
see https://stackoverflow.com/q/61070925/2142577

I'm fine with disabling `fail-fast`

**Comment by kshivakumar** [comment]
There were two groups of errors:
1. Cannot find implementation or library stub for module named "colorama"
2. Cannot find implementation or library stub for module named "pytest"
Both had the same root cause - `pytest` and `colorama` packages do not have type annotations that mypy looks for by default. 

There are two ways to fix this
- Install stub packages to pytest and colorama([types-colorama](https://pypi.org/project/types-colorama/))
- Suppress the errors

I decided to suppress the errors because:
1. `colorama` is used only at once place to handle Windows platform(api.py)
2. `pytest` is a dev dependency

I originally intended to suppress the errors by adding markers inside any of the config files - tox.ini, pyproject.toml, create mypy.ini. But no matter which config file I tried, I was not able to make it work.

[`mypy`](https://mypy.readthedocs.io/en/stable/config_file.html#the-mypy-configuration-file) looks for configuration in .mypy.ini and pyproject.toml files whereas [`pytest-mypy`](https://pypi.org/project/pytest-mypy/) looks for the config in mypy.ini and conftest.py. This creates confusion where exactly the mypy markers are supposed to go.

I finally decided to add `type: ignore` at places where we are importing `colorama` and `pytest`.

**Comment by kshivakumar** [comment]
> I'm fine with disabling fail-fast
Never mind, the existing behaviour actually makes sense.

**Comment by laike9m** [comment]
Ignoring the error makes sense to me. Thank you again!

**Pull request merged**
